# Generated by Django 4.0.10 on 2023-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactus_created_at_user_created_at_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='redeem_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
