# Generated by Django 4.0.10 on 2023-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_a', models.TextField()),
                ('choice_b', models.TextField()),
                ('Choice_c', models.TextField()),
                ('choice_d', models.TextField()),
                ('correct_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
